name: 3.15-log-app
run-name: ${{ github.actor }} is testing a serverless platform with OIDC and test log on the main workflow
on: 
  push:
    branches: 
      - dev
      - main
  pull_request:
    branches: 
      - main

# permission can be added at job level or workflow level     
permissions: 
  id-token: write   # This is required for requesting the JWT 


jobs: 
  predeploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job is automatically triggered by a ${{ github.event_name }} event."

  install-dependencies:
    runs-on: ubuntu-latest
    needs: predeploy
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run installation of dependencies commands
        run: npm ci

  unit-testing:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run installation of dependencies commands
        run: npm ci
      - name: Run unit testing command
        run: npm test

  get-secret:
    runs-on: ubuntu-latest
    needs: unit-testing
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::255945442255:role/test-oidc
          aws-region: ${{ secrets.AWS_REGION }}
      - name: aws cli show Secret
        run: |
          aws secretsmanager get-secret-value --secret-id POHLENG-SECRET
      - name: aws cli show SSM
        run: |
          aws ssm get-parameter --name pohleng-parameter

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: get-secret
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - name: serverless deploy
      uses: serverless/github-action@v3.2
      with:
        args: deploy
      env:
        AWS_ACCESS_KEY_ID:  ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}  
        




