name: 3.15-log-app-test
run-name: ${{ github.actor }} is testing a serverless platform with OIDC and test log
on: 
  push:
    branches:
      - dev

# permission can be added at job level or workflow level     
permissions: 
  id-token: write   # This is required for requesting the JWT 
    
jobs: 
  predeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Display Event Name
        run: echo "The job is automatically triggered by a ${{ github.event_name }} event."

  get-secret:
    runs-on: ubuntu-latest
    steps:
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v2
          with:
            role-to-assume: arn:aws:iam::255945442255:role/test-oidc
            aws-region: ${{ secrets.AWS_REGION }}
        - name: aws cli show Secret
          run: |
            aws secretsmanager get-secret-value --secret-id POHLENG-SECRET
        - name: aws cli show SSM
          run: |
            aws ssm get-parameter --name pohleng-parameter


  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Check out repository code
          uses: actions/checkout@v3
        - name: Run installation of dependencies commands
          run: npm ci
        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v2
          with:
            role-to-assume: arn:aws:iam::255945442255:role/test-oidc
            aws-region: ${{ secrets.AWS_REGION }}
        - name: Install Serverless Framework
          run: npm install -g serverless
        - name: Serverless Deploy
          run: serverless deploy --verbose        